<a href="https://colab.research.google.com/github/bobyuwono/-bobyuwono-.github.io/blob/master/membuat_data_series_menjadi_feature_dan_label_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [15]:
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt
print(tf.__version__)

2.2.0


In [24]:
dataset = tf.data.Dataset.range(10)
dataset = dataset.window(5, shift=1, drop_remainder=True)
dataset = dataset.flat_map(lambda window: window.batch(5))
for window in dataset:
  print(window.numpy())


[0 1 2 3 4]
[1 2 3 4 5]
[2 3 4 5 6]
[3 4 5 6 7]
[4 5 6 7 8]
[5 6 7 8 9]


sekarang membagi data menjadi feature dan label
dengan ide membagi array menjadi feature = array[ :-1] dan label = array[ -1]

tidak lupa, setelah  dibagi, datanya di shuffle


In [26]:
dataset = tf.data.Dataset.range(10)
dataset = dataset.window(5, shift=1, drop_remainder=True)
dataset = dataset.flat_map(lambda window: window.batch(5))

#dibagi
dataset = dataset.map(lambda window: (window[:-1], window[-1:]))

#shuffle dulu
buffer_size_for_shuffling = 10
dataset = dataset.shuffle(    buffer_size=buffer_size_for_shuffling, seed=None, reshuffle_each_iteration=None )
for x,y in dataset:
  print(x.numpy(), y.numpy())
  


[4 5 6 7] [8]
[0 1 2 3] [4]
[5 6 7 8] [9]
[1 2 3 4] [5]
[3 4 5 6] [7]
[2 3 4 5] [6]


buat dataset menjadi 2 batch untuk setiap value

In [27]:
dataset = tf.data.Dataset.range(10)
dataset = dataset.window(5, shift=1, drop_remainder=True)
dataset = dataset.flat_map(lambda window: window.batch(5))

#dibagi
dataset = dataset.map(lambda window: (window[:-1], window[-1:]))

#shuffle dulu
buffer_size_for_shuffling = 10
dataset = dataset.shuffle(    buffer_size=buffer_size_for_shuffling, seed=None, reshuffle_each_iteration=None )

dataset = dataset.batch(2).prefetch(1)
for x,y in dataset:
  print("x= ", x.numpy())
  print("y= ", y.numpy())

x=  [[0 1 2 3]
 [3 4 5 6]]
y=  [[4]
 [7]]
x=  [[1 2 3 4]
 [4 5 6 7]]
y=  [[5]
 [8]]
x=  [[5 6 7 8]
 [2 3 4 5]]
y=  [[9]
 [6]]
